### ISSUE TITLE
Event Sign Up Form

### ISSUE THREAD

**Issue by bot190** [chopshop-166/SignInWebApp#2]
Create a form that allows signing up for events, so that we can keep track of who's going to things easier

**Comment by msoucy** [comment]
This will probably involve creating blocks during an event to account for fund raising events that are worked in blocks. Should also add a field for comments, for weird edge cases

Blocks link to events which link to the users signed up for them.
Table of blocks, table of user-block links.

Also will involve editing the forms for event creation to add block support.

**Comment by msoucy** [comment]
Split into two issues, for 1.2 we only want to be able to sign up to an event as a whole

**Comment by bot190** [comment]
I'll probably implement most of the block logic for this, but there won't be a UI to create blocks, instead creating an event will automatically create a single block the length of the event.

**Comment by msoucy** [comment]
Be careful - make sure that there's a way to upgrade an existing database that doesn't have block support

**Comment by bot190** [comment]
Completed by #140
