### ISSUE TITLE
Additional support for Guardian info

### ISSUE THREAD

**Issue by bot190** [chopshop-166/SignInWebApp#22]
- [x] Now that we track guardian info we should have a page that can display a list of guardians and their children.
- [ ] We may also need a page to update and/or merge parent info. This would be important for cases where a guardian has multiple children on the team and mistypes their phone number when registering one of the children. 
- [x] Link Mentor (or new role?) user records to parent info.

**Comment by msoucy** [comment]
When #75 gets merged, it should remove the need for that middle check box - or at least mitigate it. You'll be able to add students to a parent's profile, then delete the old profile.

**Comment by bot190** [comment]
Yeah, I think we have the capability to deal with this now. Closing this.
