### ISSUE TITLE
Add Student info table

### ISSUE THREAD

**Issue by bot190** [chopshop-166/SignInWebApp#24]
## Student Specific Info
- Student Grade [Freshman (2026), Sophomore (2025), etc ]
- Were you on an FLL or FTC team? (Not sure this is necessary, we haven't used this data for much)

**Comment by msoucy** [comment]
Do we want to move subteam here too, or is it worth keeping it on mentor accounts?

**Comment by bot190** [comment]
I think it's worth storing for mentors, so we can leave it in the User table.

**Comment by bot190** [comment]
Completed by #38
