### ISSUE TITLE
Add configurable graceperiod at end of events

### ISSUE THREAD

**Issue by bot190** [chopshop-166/SignInWebApp#61]
Add a grace period at the end of an event where it remains active so that users can signout. This should be configurable in the config file, and default to 2 hours (I think)

**Comment by msoucy** [comment]
Don't forget a separate configurable "early arrival" time

**Comment by bot190** [comment]
I've already implemented the early arrival part of this (merged directly into main shh)

**Comment by msoucy** [comment]
Press X to doubt

**Comment by bot190** [comment]
Yeah... I've lost this change. We need 2 new config options to add extra time around events to allow users to sign-in.
1. Before events
2. After events

**Comment by bot190** [comment]
Completed by #91
